name: Release Please
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          release-type: node
          package-name: '@bjerk/eslint-config'
