name: Release Please
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          release-type: node
          package-name: '@bjerk/eslint-config'
