name: Release Please
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          release-type: node
          package-name: '@bjerk/eslint-config'
