name: Release Please
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          release-type: node
          package-name: '@bjerk/eslint-config'
