name: Release Please
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          release-type: node
          package-name: '@bjerk/eslint-config'
