name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: create-bjerk-typescript

      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3

      - if: ${{ steps.release.outputs.release_created }}
        name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - if: ${{ steps.release.outputs.release_created }}
        run: yarn install

      - if: ${{ steps.release.outputs.release_created }}
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
